// <auto-generated />
using System;
using AppCore.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppCore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260801132357_ExtendVisualIdentityAppearance")]
    partial class ExtendVisualIdentityAppearance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppCore.Infrastructure.Branding.BrandingAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.ToTable("branding_assets", "app");
                });

            modelBuilder.Entity("AppCore.Infrastructure.Branding.VisualIdentitySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("BackgroundPattern")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("CompactLogoAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DarkLogoAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FaviconAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("HeaderColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<Guid?>("LightLogoAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("ShortOrganizationName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("visual_identity_settings", "app", t =>
                        {
                            t.HasCheckConstraint("CK_visual_identity_singleton", "\"Id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundColor = "#f4f6f8",
                            BackgroundPattern = "None",
                            HeaderColor = "#ffffff",
                            OrganizationName = "AppCore",
                            PrimaryColor = "#1d4ed8",
                            SecondaryColor = "#0f766e",
                            ShortOrganizationName = "Core",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1L
                        });
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.AnonymousPreSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("anonymous_pre_sessions", "security");
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsBuiltIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsProtected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            ConcurrencyStamp = "phase-04c-10000000000000000000000000000001",
                            IsArchived = false,
                            IsBuiltIn = true,
                            IsProtected = true,
                            Name = "System Administrator",
                            NormalizedName = "SYSTEM ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            ConcurrencyStamp = "phase-04c-10000000000000000000000000000002",
                            IsArchived = false,
                            IsBuiltIn = true,
                            IsProtected = false,
                            Name = "User Administrator",
                            NormalizedName = "USER ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            ConcurrencyStamp = "phase-04c-10000000000000000000000000000003",
                            IsArchived = false,
                            IsBuiltIn = true,
                            IsProtected = false,
                            Name = "Security Administrator",
                            NormalizedName = "SECURITY ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            ConcurrencyStamp = "phase-04c-10000000000000000000000000000004",
                            IsArchived = false,
                            IsBuiltIn = true,
                            IsProtected = false,
                            Name = "Application User",
                            NormalizedName = "DIRECTORATE USER"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            ConcurrencyStamp = "phase-04c-10000000000000000000000000000005",
                            IsArchived = false,
                            IsBuiltIn = true,
                            IsProtected = false,
                            Name = "Manager / Approver",
                            NormalizedName = "MANAGER / APPROVER"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            ConcurrencyStamp = "phase-04c-10000000000000000000000000000006",
                            IsArchived = false,
                            IsBuiltIn = true,
                            IsProtected = false,
                            Name = "Auditor / Reporting User",
                            NormalizedName = "AUDITOR / REPORTING USER"
                        });
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("AuthorizationVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("FailedLoginWindowStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsProtectedOwner")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MfaState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TemporarilyThrottledUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("\"NormalizedEmail\" IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.BootstrapProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProtectedOwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("bootstrap_progress", "security", t =>
                        {
                            t.HasCheckConstraint("CK_bootstrap_progress_singleton", "\"Id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            State = "NotStarted",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.MfaAuthenticator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastAcceptedTimeStep")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("ProtectedSecret")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"RevokedAtUtc\" IS NULL");

                    b.ToTable("mfa_authenticators", "security");
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.MfaLoginChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnonymousPreSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuthenticatorId")
                        .HasColumnType("uuid");

                    b.Property<long>("AuthorizationVersionAtIssue")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("InvalidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousPreSessionId");

                    b.HasIndex("AuthenticatorId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"ConsumedAtUtc\" IS NULL AND \"InvalidatedAtUtc\" IS NULL");

                    b.ToTable("mfa_login_challenges", "security");
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.MfaRecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer");

                    b.Property<byte[]>("KeyedHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ConsumedAtUtc");

                    b.ToTable("mfa_recovery_codes", "security");
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.PasswordHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("password_history", "security");
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.PermissionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Assurance")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("permissions", "security");

                    b.HasData(
                        new
                        {
                            Id = "Users.View",
                            Assurance = "Sensitive",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Users.Create",
                            Assurance = "HighRisk",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Users.Update",
                            Assurance = "HighRisk",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Users.Enable",
                            Assurance = "HighRisk",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Users.Disable",
                            Assurance = "HighRisk",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Users.Suspend",
                            Assurance = "HighRisk",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Users.Archive",
                            Assurance = "HighRisk",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Users.Restore",
                            Assurance = "HighRisk",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Users.ResetPassword",
                            Assurance = "HighRisk",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Users.IssueActivation",
                            Assurance = "HighRisk",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Users.ResetMfa",
                            Assurance = "HighRisk",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Users.RevokeAuthenticators",
                            Assurance = "HighRisk",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Users.IssueMfaRecovery",
                            Assurance = "HighRisk",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Roles.View",
                            Assurance = "Sensitive",
                            Scope = "GlobalSystem"
                        },
                        new
                        {
                            Id = "Roles.Create",
                            Assurance = "HighRisk",
                            Scope = "GlobalSystem"
                        },
                        new
                        {
                            Id = "Roles.Update",
                            Assurance = "HighRisk",
                            Scope = "GlobalSystem"
                        },
                        new
                        {
                            Id = "Roles.Archive",
                            Assurance = "HighRisk",
                            Scope = "GlobalSystem"
                        },
                        new
                        {
                            Id = "Roles.AssignToUsers",
                            Assurance = "HighRisk",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Permissions.View",
                            Assurance = "Sensitive",
                            Scope = "GlobalSystem"
                        },
                        new
                        {
                            Id = "Permissions.AssignToRoles",
                            Assurance = "HighRisk",
                            Scope = "GlobalSystem"
                        },
                        new
                        {
                            Id = "Audit.Security.View",
                            Assurance = "Sensitive",
                            Scope = "GlobalSystem"
                        },
                        new
                        {
                            Id = "Audit.Security.Export",
                            Assurance = "HighRisk",
                            Scope = "GlobalSystem"
                        },
                        new
                        {
                            Id = "Sessions.ViewOwn",
                            Assurance = "Standard",
                            Scope = "OwnAccount"
                        },
                        new
                        {
                            Id = "Sessions.RevokeOwn",
                            Assurance = "Standard",
                            Scope = "OwnAccount"
                        },
                        new
                        {
                            Id = "Sessions.ViewForUser",
                            Assurance = "Sensitive",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Sessions.RevokeForUser",
                            Assurance = "HighRisk",
                            Scope = "AllUsers"
                        },
                        new
                        {
                            Id = "Sessions.RevokeGlobal",
                            Assurance = "Emergency",
                            Scope = "GlobalSystem"
                        },
                        new
                        {
                            Id = "Settings.VisualIdentity.View",
                            Assurance = "Sensitive",
                            Scope = "GlobalSystem"
                        },
                        new
                        {
                            Id = "Settings.VisualIdentity.Update",
                            Assurance = "HighRisk",
                            Scope = "GlobalSystem"
                        });
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.RestrictedRecoverySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"RevokedAtUtc\" IS NULL");

                    b.ToTable("restricted_recovery_sessions", "security");
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.RolePermissionAssignment", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", "security");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Users.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Users.Create"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Users.Update"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Users.Enable"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Users.Disable"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Users.Suspend"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Users.Archive"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Users.Restore"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Users.ResetPassword"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Users.IssueActivation"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Users.ResetMfa"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Users.RevokeAuthenticators"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Users.IssueMfaRecovery"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Roles.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Roles.Create"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Roles.Update"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Roles.Archive"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Roles.AssignToUsers"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Permissions.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Permissions.AssignToRoles"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Audit.Security.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Audit.Security.Export"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Sessions.ViewOwn"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Sessions.RevokeOwn"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Sessions.ViewForUser"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Sessions.RevokeForUser"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Sessions.RevokeGlobal"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Settings.VisualIdentity.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = "Settings.VisualIdentity.Update"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Users.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Users.Create"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Users.Update"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Users.Enable"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Users.Disable"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Users.Suspend"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Users.Archive"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Users.Restore"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Users.ResetPassword"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Users.IssueActivation"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Roles.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Roles.AssignToUsers"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Permissions.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Sessions.ViewOwn"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = "Sessions.RevokeOwn"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Users.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Users.ResetMfa"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Users.RevokeAuthenticators"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Users.IssueMfaRecovery"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Roles.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Roles.Create"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Roles.Update"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Roles.Archive"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Permissions.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Permissions.AssignToRoles"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Audit.Security.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Audit.Security.Export"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Sessions.ViewForUser"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Sessions.RevokeForUser"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Sessions.RevokeGlobal"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Sessions.ViewOwn"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = "Sessions.RevokeOwn"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000004"),
                            PermissionId = "Sessions.ViewOwn"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000004"),
                            PermissionId = "Sessions.RevokeOwn"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000005"),
                            PermissionId = "Sessions.ViewOwn"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000005"),
                            PermissionId = "Sessions.RevokeOwn"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000006"),
                            PermissionId = "Roles.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000006"),
                            PermissionId = "Permissions.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000006"),
                            PermissionId = "Audit.Security.View"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000006"),
                            PermissionId = "Sessions.ViewOwn"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000006"),
                            PermissionId = "Sessions.RevokeOwn"
                        });
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.SecurityAuditContext", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SecurityAuditEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("SecurityAuditEventId")
                        .IsUnique();

                    b.ToTable("security_audit_contexts", "security");
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.SecurityAuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("TargetUserId");

                    b.ToTable("security_audit_events", "security");
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.SecurityChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("InvalidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer");

                    b.Property<byte[]>("KeyedHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Purpose")
                        .IsUnique()
                        .HasFilter("\"ConsumedAtUtc\" IS NULL AND \"InvalidatedAtUtc\" IS NULL");

                    b.ToTable("security_challenges", "security");
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.ServerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthenticationMethods")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("AuthorizationVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("MfaVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RevokedAtUtc");

                    b.ToTable("sessions", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", "identity");
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.MfaAuthenticator", b =>
                {
                    b.HasOne("AppCore.Infrastructure.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.MfaLoginChallenge", b =>
                {
                    b.HasOne("AppCore.Infrastructure.Security.AnonymousPreSession", null)
                        .WithMany()
                        .HasForeignKey("AnonymousPreSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppCore.Infrastructure.Security.MfaAuthenticator", null)
                        .WithMany()
                        .HasForeignKey("AuthenticatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppCore.Infrastructure.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.MfaRecoveryCode", b =>
                {
                    b.HasOne("AppCore.Infrastructure.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.PasswordHistoryEntry", b =>
                {
                    b.HasOne("AppCore.Infrastructure.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.RestrictedRecoverySession", b =>
                {
                    b.HasOne("AppCore.Infrastructure.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.RolePermissionAssignment", b =>
                {
                    b.HasOne("AppCore.Infrastructure.Security.PermissionRecord", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppCore.Infrastructure.Security.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.SecurityAuditContext", b =>
                {
                    b.HasOne("AppCore.Infrastructure.Security.SecurityAuditEvent", "SecurityAuditEvent")
                        .WithOne()
                        .HasForeignKey("AppCore.Infrastructure.Security.SecurityAuditContext", "SecurityAuditEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityAuditEvent");
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.SecurityChallenge", b =>
                {
                    b.HasOne("AppCore.Infrastructure.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Infrastructure.Security.ServerSession", b =>
                {
                    b.HasOne("AppCore.Infrastructure.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("AppCore.Infrastructure.Security.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AppCore.Infrastructure.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AppCore.Infrastructure.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("AppCore.Infrastructure.Security.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Infrastructure.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AppCore.Infrastructure.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
